# optimizer
batch_size_train: 32 #16 
batch_size_test: 1 #32 
image_size: 224
weight_decay: 0.0
init_lr: 2e-5
min_lr: 2e-5
max_epoch: 3


############### Ignore Below -- These will not be used ############### 
# TODO: delete these
vqa_root: '/export/share/datasets/vision/VQA/Images/mscoco/' #followed by train2014/
vg_root: '/export/share/datasets/vision/visual-genome/'  #followed by image/
train_files: ['vqa_train','vqa_val','vg_qa']
ann_root: 'annotation'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth'
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
k_test: 128
inference: 'generate'
